/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/group/new`; params?: Router.UnknownInputParams; } | { pathname: `/group/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/group/[id]/split/new`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/group/[id]/split/[splitId]/detail`, params: Router.UnknownInputParams & { id: string | number;splitId: string | number; } } | { pathname: `/group/[id]/split/[splitId]/settle`, params: Router.UnknownInputParams & { id: string | number;splitId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/group/new`; params?: Router.UnknownOutputParams; } | { pathname: `/group/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/group/[id]/split/new`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/group/[id]/split/[splitId]/detail`, params: Router.UnknownOutputParams & { id: string;splitId: string; } } | { pathname: `/group/[id]/split/[splitId]/settle`, params: Router.UnknownOutputParams & { id: string;splitId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/group/new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/group/new`; params?: Router.UnknownInputParams; } | `/group/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/group/${Router.SingleRoutePart<T>}/split/new${`?${string}` | `#${string}` | ''}` | `/group/${Router.SingleRoutePart<T>}/split/${Router.SingleRoutePart<T>}/detail${`?${string}` | `#${string}` | ''}` | `/group/${Router.SingleRoutePart<T>}/split/${Router.SingleRoutePart<T>}/settle${`?${string}` | `#${string}` | ''}` | { pathname: `/group/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/group/[id]/split/new`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/group/[id]/split/[splitId]/detail`, params: Router.UnknownInputParams & { id: string | number;splitId: string | number; } } | { pathname: `/group/[id]/split/[splitId]/settle`, params: Router.UnknownInputParams & { id: string | number;splitId: string | number; } };
    }
  }
}
